<a href="https://colab.research.google.com/github/Arpan-mukherjee2023/Data-Science-2/blob/main/NN_MODULE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Neural Network with hidden layer

Now let us create a NN with 5 input features and 2 layer where 1st layer contains 3 bias and second layer contains 1 bias and then it predicts the output. The hidden layer uses RelU and the output uses Sigmoid function.

In [1]:
import torch
import torch.nn as nn

In [2]:
class NeuralNetwork(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [3]:
features = torch.rand(10, 5)

model = NeuralNetwork(features.shape[1])

model(features)

tensor([[0.6199],
        [0.6053],
        [0.6183],
        [0.6100],
        [0.6162],
        [0.6130],
        [0.6203],
        [0.6127],
        [0.6094],
        [0.6130]], grad_fn=<SigmoidBackward0>)

In [5]:
model.linear2.weight

Parameter containing:
tensor([[ 0.2211,  0.1950, -0.2957]], requires_grad=True)

A NN can have multiple layers and passing the out variable through each layer eachtime is hectic hence we can use containers to make it much more simple.

In [10]:
class NeuralNetwork2(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )


  def forward(self, features):
    out = self.network(features)

    return out

In [11]:
model = NeuralNetwork2(features.shape[1])

model(features)

tensor([[0.3730],
        [0.3715],
        [0.3735],
        [0.3755],
        [0.3742],
        [0.3707],
        [0.3725],
        [0.3771],
        [0.3784],
        [0.3740]], grad_fn=<SigmoidBackward0>)

Now lets improve the training pipeline more to ensure that everything works fine

In [26]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [14]:
df = pd.read_csv('/content/drive/MyDrive/dataset/breast-cancer.csv')

In [16]:
df.drop(columns=['id'], inplace=True)

In [17]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [19]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [21]:
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [22]:
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

In [27]:
X_train = torch.from_numpy(X_train.astype(np.float32))
X_test = torch.from_numpy(X_test.astype(np.float32))

In [28]:
y_train = torch.from_numpy(y_train.astype(np.float32))
y_test = torch.from_numpy(y_test.astype(np.float32))

In [42]:
class NeuralNetwork3(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

  def loss_function(self, y_pred, y):
    lepsilon = 1e-7
    y_pred = torch.clamp(y_pred, lepsilon, 1-lepsilon)
    loss = -(y * torch.log(y_pred) + (1 - y) *  torch.log(1 - y_pred)).mean()
    return loss

In [43]:
model = NeuralNetwork3(X_train.shape[1])

In [47]:
learning_rate = 0.01
num_epochs = 100

for epoch in range(num_epochs):
  y_pred = model(X_train)

  loss = model.loss_function(y_pred, y_train)

  loss.backward()

  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad


  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  if epoch % 10 == 0:
    print(f'epoch: {epoch}, loss: {loss.item()}')




epoch: 0, loss: 0.6631447672843933
epoch: 10, loss: 0.6631447076797485
epoch: 20, loss: 0.6631445288658142
epoch: 30, loss: 0.6631445288658142
epoch: 40, loss: 0.6631444692611694
epoch: 50, loss: 0.6631444096565247
epoch: 60, loss: 0.6631443500518799
epoch: 70, loss: 0.6631442308425903
epoch: 80, loss: 0.6631441712379456
epoch: 90, loss: 0.6631441116333008


In [48]:
with torch.no_grad():
  y_pred = model.forward(X_test)
  y_pred_class = y_pred.round()
  acc = accuracy_score(y_test, y_pred_class)
print(acc)

0.6491228070175439


In [49]:
class NeuralNetwork4(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [58]:
import torch.optim as opt
model = NeuralNetwork4(X_train.shape[1])
loss_function = nn.BCELoss()

optimiser = opt.SGD(model.parameters(), lr=learning_rate)
# optimiser

In [59]:
learning_rate = 0.01
num_epochs = 100

for epoch in range(num_epochs):
  y_pred = model(X_train)

  loss = loss_function(y_pred, y_train.view(-1,1))


  # it is good to use the cleaning of gradients before the backward pass as it can make the working fluent and better
  optimiser.zero_grad()

  loss.backward()

  optimiser.step()


  if epoch % 10 == 0:
    print(f'epoch: {epoch}, loss: {loss.item()}')




epoch: 0, loss: 0.6597960591316223
epoch: 10, loss: 0.5394042134284973
epoch: 20, loss: 0.4648245573043823
epoch: 30, loss: 0.41443678736686707
epoch: 40, loss: 0.37763044238090515
epoch: 50, loss: 0.34922540187835693
epoch: 60, loss: 0.32644355297088623
epoch: 70, loss: 0.3076481223106384
epoch: 80, loss: 0.2918023467063904
epoch: 90, loss: 0.27821290493011475


In [60]:
with torch.no_grad():
  y_pred = model.forward(X_test)
  y_pred_class = y_pred.round()
  acc = accuracy_score(y_test, y_pred_class)
print(acc)

0.9473684210526315
